openapi: 3.0.0
info:
  title: Task Manager API
  version: 1.0.0
  description: Swagger API Documentation for Task Manager
servers:
  - url: https://localhost:3033
    description: local development server  

paths:
  /users/register:
    post:
      summary: Register for new user
      responses:
        "201":
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      role:
                        type: string

        "400":
          description: Bad request
